#cfg:
#  image: mickep76/etcdrest-example:latest
#  command: tail -f /dev/null
#  volumes:
#  - /app/schemas
#  - /app/templates
#  - /app/etc
api:
  image: mickep76/etcdrest:latest
  ports:
  - 8080:8080
#  links:
#  - db:ETCD
#  volumes_from:
#  - cfg
#db:
#  image: quay.io/coreos/etcd:latest
